sonar.projectKey=dvna
sonar.projectName=DVNA
sonar.projectVersion=1.0

sonar.sources=.

sonar.sourceEncoding=UTF-8

sonar.host.url=http://host.docker.internal:9000

sonar.login=${env.SONAR_TOKEN}

sonar.exclusions=node_modules/**,coverage/**,.git/**
